### ISSUE TITLE
Pagination for `Row` Listing on `Table` route [$20]

### ISSUE THREAD

**Issue by LemonAndroid** [LemonAndroid/natural-frontend#2]
Still todo: 
* https://github.com/MangoSmoothie101010/natural-frontend/issues/10 
* https://github.com/MangoSmoothie101010/natural-frontend/issues/9

**Comment by MangoSmoothie101010** [comment]
* Rows have to be stripped from table index api endpoint.
* Not properly working in prod env
* Slow loading times after second infinity fetch

**Comment by rsercano** [comment]
is this issue done ?

**Comment by MangoSmoothie101010** [comment]
Hey, 

No. The todos listed in the description are still open.

**Comment by LemonAndroid** [comment]
This will be closed and I will reallocate the funds. Please comment here if you already started work and still want to claim the bounty.
